(autoload 'git-commit--save-and-exit            "git-commit" "" nil)
(autoload 'git-commit-commit                    "git-commit" "" t)
(autoload 'git-commit-git-config-var            "git-commit" "" nil)
(autoload 'git-commit-first-env-var             "git-commit" "" nil)
(autoload 'git-commit-committer-name            "git-commit" "" nil)
(autoload 'git-commit-committer-email           "git-commit" "" nil)
(autoload 'git-commit-find-pseudo-header-position "git-commit" "" nil)
(autoload 'git-commit-insert-header             "git-commit" "" nil)
(autoload 'git-commit-insert-header-as-self     "git-commit" "" nil)
(autoload 'git-define-git-commit-self           "git-commit" "" t 'macro)
(autoload 'git-define-git-commit                "git-commit" "" t 'macro)
(autoload 'git-commit-font-lock-diff            "git-commit" "" nil)
(autoload 'git-commit-mode                      "git-commit" "" t)
(provide 'git-commit-mode-epackage-autoloads)
